apiVersion: v1
kind: Service
metadata:
  name: endgame
  namespace: endgame
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
