apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: endgame
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: 2380
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

