apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: endgame
  namespace: endgame
webhooks:
- clientConfig:
    caBundle: "" 
    service:
      name: endgame
      namespace: endgame
      path: /etcd
  failurePolicy: Ignore
  name: test.endgame.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - pods
  sideEffects: Unknown
